### PR TITLE
Updates snyk plugin to use recent backstage

### LINKED ISSUE #36: [🐛] Error: No Snyk org/project-ids listed
- `node -v`: v14.17.5
- `npm -v`: 6.14.14
- OS: (e.g. OSX, Linux, Windows, ...) Debian GNU/Linux 10 (buster)

### Expected behaviour
Installing plugin on a backstage application should work.

### Actual behaviour
In the "Security" (Snyk) tab, I'm getting below error:
> No Snyk org/project-ids listed

This is happening probably due to [this](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/develop/src/components/SnykEntityComponent/SnykOverviewComponent.tsx#L22-L24) code:
```
if (!entity || !entity?.metadata.name) {
  return <>No Snyk org/project-ids listed</>;
}
```
But our projects have `metadata.name`, `metadata.annotations.snyk.io/org-name` and `metadata.annotations.snyk.io/project-ids` defined:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: foo
  description: foo
  annotations:
    snyk.io/org-name: foo
    snyk.io/project-ids: foo
```

### Steps to reproduce
- Create a backstage application.
- Run `yarn backstage-cli versions:bump` to ensure packages are updated.
- Pin `tech-radar` to `0.4.4` due to [this](https://github.com/Qix-/color/issues/213#issuecomment-897036602) issue.

### PR DESCRIPTION
**Pull request by punkle**
- [ ] Tests written and linted [ℹ︎](https://github.com/snyk-tech-services/general/wiki/Tests)
- [ ] Commit history is tidy & follows Contributing guidelines [ℹ︎](./CONTRIBUTING.md#commit-messages)

### What this does

The snyk backstage plugin does not work with current versions of backstage. This change updates the dependencies to make it work again.

Fixes #36

### CODE REVIEW

**Comment by punkle** [comment]
@aarlaud How might I get sign the license agreement?

**Comment by aarlaud** [comment]
hey @punkle thanks for the contribution. I've added you to the .clabot file. You might need to rebase to get the change, but clabot works that way. you should be fine from there and we can merge the branch then.

**Comment by punkle** [comment]
@aarlaud Ive rebased the pull request branch. Thanks for adding me to the cla.

**Comment by punkle** [comment]
Thanks for merging @aarlaud. I wonder when I can expect to see this change on npm?

**Pull request merged**
