### PR TITLE
fix(api): update `targets` endpoint to use up-to-date `projects` endpoint

### PR DESCRIPTION
**Pull request by Silthus**
- [ ] Tests written and linted [ℹ︎](https://github.com/snyk-tech-services/general/wiki/Tests)
- [ ] Commit history is tidy & follows Contributing guidelines [ℹ︎](./CONTRIBUTING.md#commit-messages)

### What this does

I noticed an edge case in the implementation of my last PR while testing this with our production setup. In the case where no projects are found in any targets the project list will be empty. This causes the API to fetch all projects from all configured orgs causing a very long list and loading time.

Before the change an error was thrown. This should also be the case for the multi org setup.

### Notes for the reviewer

_Instructions on how to run this locally, background context, what to review, questions…_

### More information

- [Link to documentation]()

### Screenshots

_Visuals that may help the reviewer_

### CODE REVIEW

**Comment by Silthus** [comment]
After diving deeper into the issue, it seems as the root cause is an underlying problem with the usage of the snyk api.

If following the official documentation, there is not `targets` endpoint, only a `projects` one that takes `names` and not `displayName` as the parameter.
The API requests of the snyk plugin always fail with a 404 error, which then comes back to the error this PR fixes.

But I think the root cause is that the snyk client in this project somehow does not match the official snyk api. How is that? Even when I search through every version of the api there has never been a `targets` endpoint. At least officially.

https://apidocs.snyk.io/?version=2024-01-23#get-/orgs/-org_id-/projects

**Comment by aarlaud** [comment]
I think there is a bit of confusion between targets and projects. Will need to clarify things a little more in the documentation I suppose.
I'll attempt reproducing your situation with targets from multiple orgs not matching any project and pulling all the projects in turn.

**Comment by Silthus** [comment]
Thanks, the upstream fix from you fixed the loading of all projects if no target is found. However the current API still returns a 404 for the `targets` endpoint:

image

In the API specs (see link above) there definitly is no targets endpoint listed, so for me at least, the 404 is expected and from my perspective the change to only query the projects endpoint by id or name should fix this.

I am handing this over to my team, as today is my last day at Interhyp. I will however keep an eye out on this issue as well, if any questions arise.

/cc @stephanhcb @roshick @tstollin @kraffael @mplushnikov

**Comment by Roshick** [comment]
So my previous change solved the API request problems, unfortunately there still remain issues. As I'm on vacation starting tomorrow, I will have a deeper look at this next week.

**Comment by Roshick** [comment]
https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/191 fixes the remaining issues, this one can be closed then.

**Pull request closed without merging**
