### PR TITLE
copy mdi logos to reduce the size of backstage bundle

### PR DESCRIPTION
**Pull request by punkle**
- [ ] Tests written and linted [ℹ︎](https://github.com/snyk-tech-services/general/wiki/Tests)
- [ ] Commit history is tidy & follows Contributing guidelines [ℹ︎](./CONTRIBUTING.md#commit-messages)

### What this does

The size of the mdi/js library when it is built into the backstage bundle is more than 2mb. It contributes to quite a lot of static content that needs to be downloaded to run backstage. This change copies the exact svgs neccessary for this plugin into the code.

### Notes for the reviewer

_Instructions on how to run this locally, background context, what to review, questions…_

### More information

- [Link to documentation]()

### Screenshots

_Visuals that may help the reviewer_

### CODE REVIEW

**Comment by punkle** [comment]
I have asked the backstage community why the tree shaking might not be working correctly. https://discord.com/channels/687207715902193673/995973463208644678/1026858154874650684

**Comment by lili2311** [comment]
hi @punkle thanks for your cintribution, we will review this. In the mean time please could you update the commit message to follow the [semantic release](https://github.com/semantic-release/semantic-release) style please so our release will pick up the versioning correctly? `fix: <your message>` sounds appropriate here

**Comment by punkle** [comment]
@lili2311 done thanks.

**Comment by punkle** [comment]
Ive created a new pull request against develop here https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/107

**Pull request closed without merging**
